- hosts: all
  user: admin
  become: true
  tasks:
  - name: Set password vagrant
    shell: echo 'vagrant:vagrant' | chpasswd
  - name: Enabled password in sshd
    lineinfile:
      path: /etc/ssh/sshd_config
      regex: '^#?PasswordAuthentication\s+no'
      line: PasswordAuthentication yes
    notify:
      - restart sshd
  - name: Force ethX interfaces
    ansible.builtin.lineinfile:
      path: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
      line: 'GRUB_CMDLINE_LINUX_DEFAULT="net.ifnames=0 biosdevname=0"'
    notify:
      - Regen GRUB
  - name: Install python3 and pip3
    ansible.builtin.apt:
      name:
        - python3
        - python3-pip
      state: present
      update_cache: yes
  - name: Upgrade pip and setuptools
    pip:
      name:
        - pip
        - setuptools
      extra_args: --upgrade
  - name: Install dependance package
    pip:
      name:
        - pyyaml
        - flatdict
      extra_args: --upgrade
  - name: Install ganeti
    ansible.builtin.apt:
      name:
        - jq
        - ganeti
        - ganeti-os-noop
      state: present
      update_cache: yes
  - name: create bridge
    template:
      src: br_gnt.j2
      dest: /etc/network/interfaces
      owner: root
      group: root
      mode: 0644
    notify:
      - restart network
  - name: Create /root.ssh
    file:
      path: /root/.ssh
      state: directory
  - name: Send file-storage-paths
    copy:
      src: file-storage-paths
      dest: /etc/ganeti/file-storage-paths
  # hostname
  - name: Send hostname
    template:
      src: hostname.j2
      dest: /etc/hostname
    notify:
      - reload hostname
  - name: send hosts
    template:
      src: hosts.j2
      dest: /etc/hosts
  vars:
    ansible_python_interpreter: /usr/bin/python3
    host_group_name: "{{group_names | first}}"
    host_name: "{{inventory_hostname}}"
    host_ip: "{{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}"
    host_gateway: "{{hostvars[inventory_hostname]['ansible_default_ipv4']['gateway']}}"
    host_netmask: "{{hostvars[inventory_hostname]['ansible_default_ipv4']['netmask']}}"
    host_interface: "{{hostvars[inventory_hostname]['ansible_default_ipv4']['interface']}}"
  handlers:
    - name: restart sshd
      ansible.builtin.systemd:
        state: restarted
        name: sshd
    - name: reload hostname
      shell: hostname -F /etc/hostname
    - name: Regen GRUB
      ansible.builtin.shell: grub-mkconfig -o /boot/grub/grub.cfg
    - name: restart network
      ansible.builtin.systemd:
        state: restarted
        name: networking

