- hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Remove Instance
      ganeti.cli.gnt_instance:
        name: instance_state
        state: absent
