- hosts: all
  become: true
  tasks:
    - name: Create Instance
      ganeti.cli.ganeti_instance_cli:
        name: test
        state: present
        params:
          disk_template: file
          disks:
            - size: 10G
          os_type: noop
          name_check: False
          ip_check: False
          nics:
            - name: test
              link: br_gnt
              mode: bridged
